"""initial_schema

Revision ID: 7c1badcb31be
Revises: 
Create Date: 2026-06-12 07:49:53.646228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '7c1badcb31be'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cursos',
    sa.Column('idCurso', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombreCurso', sa.String(length=30), nullable=False),
    sa.Column('grado', sa.String(length=20), nullable=False),
    sa.Column('jornada', sa.String(length=10), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('area', sa.String(length=50), nullable=True),
    sa.Column('intensidadHoraria', sa.Integer(), nullable=True),
    sa.Column('descripcion', sa.String(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('fechaCreacion', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('idCurso'),
    schema='public'
    )
    op.create_table('especializaciones',
    sa.Column('idEspecializacion', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombreEspecializacion', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.String(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('idEspecializacion'),
    schema='public'
    )
    op.create_table('materias',
    sa.Column('idMateria', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombreMateria', sa.String(length=100), nullable=False),
    sa.Column('codigoMateria', sa.String(length=20), nullable=False),
    sa.Column('activa', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('idMateria'),
    schema='public'
    )
    op.create_table('roles',
    sa.Column('idRol', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombreRol', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('idRol'),
    schema='public'
    )
    op.create_table('tiposnovedad',
    sa.Column('idTipoNovedad', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombreTipo', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('nivelGravedad', sa.String(length=10), nullable=False),
    sa.Column('requiereAccion', sa.Boolean(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('idTipoNovedad'),
    schema='public'
    )
    op.create_table('Horario',
    sa.Column('idHorario', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('idCurso', sa.Integer(), nullable=False),
    sa.Column('idMateria', sa.Integer(), nullable=False),
    sa.Column('dia', sa.String(length=10), nullable=False),
    sa.Column('horaInicio', sa.Time(), nullable=False),
    sa.Column('horaFin', sa.Time(), nullable=False),
    sa.Column('salon', sa.String(length=20), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['idCurso'], ['public.cursos.idCurso'], ),
    sa.ForeignKeyConstraint(['idMateria'], ['public.materias.idMateria'], ),
    sa.PrimaryKeyConstraint('idHorario'),
    schema='public'
    )
    op.create_table('usuario',
    sa.Column('idUsuario', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tipoDocumento', sa.String(length=10), nullable=False),
    sa.Column('numeroDocumento', sa.String(length=20), nullable=False),
    sa.Column('primerNombre', sa.String(length=50), nullable=False),
    sa.Column('segundoNombre', sa.String(length=50), nullable=True),
    sa.Column('primerApellido', sa.String(length=50), nullable=False),
    sa.Column('segundoApellido', sa.String(length=50), nullable=True),
    sa.Column('genero', sa.String(length=1), nullable=True),
    sa.Column('direccion', sa.String(length=200), nullable=True),
    sa.Column('correo', sa.String(length=45), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('estado', sa.Boolean(), nullable=False),
    sa.Column('fechaRegistro', sa.DateTime(), nullable=False),
    sa.Column('ultimoAcceso', sa.DateTime(), nullable=True),
    sa.Column('idRol', sa.Integer(), nullable=False),
    sa.Column('auth_id', sa.UUID(), nullable=True),
    sa.Column('idUsuario_uuid', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['idRol'], ['public.roles.idRol'], ),
    sa.PrimaryKeyConstraint('idUsuario'),
    schema='public'
    )
    op.create_table('administrador',
    sa.Column('idAdministrador', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('idUsuario', sa.Integer(), nullable=False),
    sa.Column('cargo', sa.String(length=100), nullable=False),
    sa.Column('nivelAcceso', sa.String(length=10), nullable=False),
    sa.Column('estado', sa.String(length=10), nullable=False),
    sa.Column('fechaAsignacion', sa.Date(), nullable=False),
    sa.Column('fechaFin', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['idUsuario'], ['public.usuario.idUsuario'], ),
    sa.PrimaryKeyConstraint('idAdministrador'),
    schema='public'
    )
    op.create_table('estudiantes',
    sa.Column('idEstudiante', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('idUsuario', sa.Integer(), nullable=False),
    sa.Column('codigoEstudiante', sa.String(length=20), nullable=False),
    sa.Column('fechaIngreso', sa.Date(), nullable=False),
    sa.Column('fechaEgreso', sa.Date(), nullable=True),
    sa.Column('estado', sa.String(length=10), nullable=False),
    sa.Column('idCursoActual', sa.Integer(), nullable=True),
    sa.Column('Horario_idHorario', sa.Integer(), nullable=True),
    sa.Column('fechaRegistro', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['idCursoActual'], ['public.cursos.idCurso'], ),
    sa.ForeignKeyConstraint(['idUsuario'], ['public.usuario.idUsuario'], ),
    sa.PrimaryKeyConstraint('idEstudiante'),
    schema='public'
    )
    op.create_table('profesores',
    sa.Column('idProfesor', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('idUsuario', sa.Integer(), nullable=False),
    sa.Column('codigoProfesor', sa.String(length=20), nullable=False),
    sa.Column('titulo', sa.String(length=100), nullable=False),
    sa.Column('nivelEstudios', sa.String(length=50), nullable=False),
    sa.Column('fechaVinculacion', sa.Date(), nullable=False),
    sa.Column('estado', sa.String(length=10), nullable=False),
    sa.Column('fechaRegistro', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['idUsuario'], ['public.usuario.idUsuario'], ),
    sa.PrimaryKeyConstraint('idProfesor'),
    schema='public'
    )
    op.create_table('Asistencia',
    sa.Column('idAsistencia', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('idEstudiante', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('estado', sa.String(length=15), nullable=False),
    sa.Column('observacion', sa.Text(), nullable=True),
    sa.Column('registradoPor', sa.Integer(), nullable=False),
    sa.Column('fechaRegistro', sa.DateTime(), nullable=False),
    sa.Column('tipo', sa.Text(), nullable=True),
    sa.Column('codigo_qr', sa.Text(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['idEstudiante'], ['public.estudiantes.idEstudiante'], ),
    sa.ForeignKeyConstraint(['registradoPor'], ['public.usuario.idUsuario'], ),
    sa.PrimaryKeyConstraint('idAsistencia'),
    schema='public'
    )
    op.create_table('Asistencia_Aula',
    sa.Column('idAsistenciaAula', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('idEstudiante', sa.Integer(), nullable=False),
    sa.Column('idHorario', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('estado', sa.String(length=15), nullable=False),
    sa.Column('observacion', sa.Text(), nullable=False),
    sa.Column('registradoPor', sa.Integer(), nullable=False),
    sa.Column('fechaRegistro', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['idEstudiante'], ['public.estudiantes.idEstudiante'], ),
    sa.ForeignKeyConstraint(['idHorario'], ['public.Horario.idHorario'], ),
    sa.ForeignKeyConstraint(['registradoPor'], ['public.usuario.idUsuario'], ),
    sa.PrimaryKeyConstraint('idAsistenciaAula'),
    schema='public'
    )
    op.create_table('Reportes',
    sa.Column('idReporte', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombreReporte', sa.Text(), nullable=False),
    sa.Column('tipoReporte', sa.Text(), nullable=False),
    sa.Column('fechaGeneracion', sa.Date(), nullable=False),
    sa.Column('fechaInicio', sa.Date(), nullable=False),
    sa.Column('fechaFin', sa.Date(), nullable=False),
    sa.Column('estado', sa.Text(), nullable=False),
    sa.Column('idAdministrador', sa.Integer(), nullable=False),
    sa.Column('parametros', sa.String(length=1), nullable=False),
    sa.Column('archivoGenerado', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['idAdministrador'], ['public.administrador.idAdministrador'], ),
    sa.PrimaryKeyConstraint('idReporte'),
    schema='public'
    )
    op.create_table('asignaciones',
    sa.Column('idAsignacion', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('idProfesor', sa.Integer(), nullable=False),
    sa.Column('idCurso', sa.Integer(), nullable=False),
    sa.Column('idMateria', sa.Integer(), nullable=False),
    sa.Column('fechaAsignacion', sa.DateTime(), nullable=False),
    sa.Column('fechaFinalizacion', sa.Date(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['idCurso'], ['public.cursos.idCurso'], ),
    sa.ForeignKeyConstraint(['idMateria'], ['public.materias.idMateria'], ),
    sa.ForeignKeyConstraint(['idProfesor'], ['public.profesores.idProfesor'], ),
    sa.PrimaryKeyConstraint('idAsignacion'),
    schema='public'
    )
    op.create_table('estudianteips',
    sa.Column('idEstudiante', sa.Integer(), nullable=False),
    sa.Column('idIPS', sa.Integer(), nullable=False),
    sa.Column('nombreIPS', sa.String(length=100), nullable=False),
    sa.Column('fechaAfiliacion', sa.Date(), nullable=False),
    sa.Column('fechaVencimiento', sa.Date(), nullable=True),
    sa.Column('tipoAfiliacion', sa.String(length=20), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['idEstudiante'], ['public.estudiantes.idEstudiante'], ),
    sa.PrimaryKeyConstraint('idEstudiante', 'idIPS'),
    schema='public'
    )
    op.create_table('notas',
    sa.Column('idNota', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('idEstudiante', sa.Integer(), nullable=False),
    sa.Column('idMateria', sa.Integer(), nullable=False),
    sa.Column('idPeriodo', sa.Integer(), nullable=False),
    sa.Column('nota', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('observacion', sa.Text(), nullable=True),
    sa.Column('fechaRegistro', sa.DateTime(), nullable=False),
    sa.Column('registradoPor', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['idEstudiante'], ['public.estudiantes.idEstudiante'], ),
    sa.ForeignKeyConstraint(['idMateria'], ['public.materias.idMateria'], ),
    sa.ForeignKeyConstraint(['registradoPor'], ['public.usuario.idUsuario'], ),
    sa.PrimaryKeyConstraint('idNota'),
    schema='public'
    )
    op.create_table('novedades',
    sa.Column('idNovedad', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('idEstudiante', sa.Integer(), nullable=False),
    sa.Column('idTipoNovedad', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('accionTomada', sa.Text(), nullable=True),
    sa.Column('registradoPor', sa.Integer(), nullable=False),
    sa.Column('fechaResolucion', sa.Date(), nullable=True),
    sa.Column('estado', sa.String(length=15), nullable=False),
    sa.ForeignKeyConstraint(['idEstudiante'], ['public.estudiantes.idEstudiante'], ),
    sa.ForeignKeyConstraint(['idTipoNovedad'], ['public.tiposnovedad.idTipoNovedad'], ),
    sa.ForeignKeyConstraint(['registradoPor'], ['public.usuario.idUsuario'], ),
    sa.PrimaryKeyConstraint('idNovedad'),
    schema='public'
    )
    op.create_table('padres',
    sa.Column('idPadre', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('idUsuario', sa.Integer(), nullable=False),
    sa.Column('idEstudiante', sa.Integer(), nullable=False),
    sa.Column('parentesco', sa.String(length=30), nullable=False),
    sa.Column('ocupacion', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['idEstudiante'], ['public.estudiantes.idEstudiante'], ),
    sa.ForeignKeyConstraint(['idUsuario'], ['public.usuario.idUsuario'], ),
    sa.PrimaryKeyConstraint('idPadre'),
    schema='public'
    )
    op.create_table('profesores_horario',
    sa.Column('idProfesor', sa.Integer(), nullable=False),
    sa.Column('idHorario', sa.Integer(), nullable=False),
    sa.Column('fechaAsignacion', sa.DateTime(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['idHorario'], ['public.Horario.idHorario'], ),
    sa.ForeignKeyConstraint(['idProfesor'], ['public.profesores.idProfesor'], ),
    sa.PrimaryKeyConstraint('idProfesor', 'idHorario'),
    schema='public'
    )
    op.create_table('profesorespecializacion',
    sa.Column('idProfesor', sa.Integer(), nullable=False),
    sa.Column('idEspecializacion', sa.Integer(), nullable=False),
    sa.Column('institucion', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['idEspecializacion'], ['public.especializaciones.idEspecializacion'], ),
    sa.ForeignKeyConstraint(['idProfesor'], ['public.profesores.idProfesor'], ),
    sa.PrimaryKeyConstraint('idProfesor', 'idEspecializacion'),
    schema='public'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profesorespecializacion', schema='public')
    op.drop_table('profesores_horario', schema='public')
    op.drop_table('padres', schema='public')
    op.drop_table('novedades', schema='public')
    op.drop_table('notas', schema='public')
    op.drop_table('estudianteips', schema='public')
    op.drop_table('asignaciones', schema='public')
    op.drop_table('Reportes', schema='public')
    op.drop_table('Asistencia_Aula', schema='public')
    op.drop_table('Asistencia', schema='public')
    op.drop_table('profesores', schema='public')
    op.drop_table('estudiantes', schema='public')
    op.drop_table('administrador', schema='public')
    op.drop_table('usuario', schema='public')
    op.drop_table('Horario', schema='public')
    op.drop_table('tiposnovedad', schema='public')
    op.drop_table('roles', schema='public')
    op.drop_table('materias', schema='public')
    op.drop_table('especializaciones', schema='public')
    op.drop_table('cursos', schema='public')
    # ### end Alembic commands ###
